// Online room = one Supabase Realtime channel per group (`pet-room:<uuid>`).
// Presence carries the roster (who's here, with which pet); broadcast events
// carry positions, chat, emotes, social pets and the battle handshake. No
// dedicated game server: Realtime relays messages, and anything that must
// agree on both screens (battles) is made deterministic via a shared seed
// resolved by pet-core's resolveBattle on each client independently.
//
// Room security note (MVP): channel names embed the group's UUID — reachable
// only by people who can read the group row (RLS) or were told the id.
// Realtime private-channel authorization is a hardening follow-up.
import { useCallback, useEffect, useRef, useState } from "react";
import type { RealtimeChannel } from "@supabase/supabase-js";
import {
  applyTossEvent,
  currentTossTurn,
  initTossGame,
  resolveBattle,
  TARGET_TOSS_GAME_CODE,
  type BattleResult,
  type BattlerSnapshot,
  type PetSaveData,
  type TossGameCore,
} from "@pet/core";
import { supabase } from "../supabase/client";
import type { GroupInfo } from "../game/useGroups";

export interface RoomMember {
  userId: string;
  name: string;
  petName: string;
  petType: string;
  stage: number;
}

export interface ChatMsg {
  id: string;
  from: string;
  name: string;
  text: string;
  at: number;
}

export interface BattleInvite {
  from: string;
  fromName: string;
  seed: number;
  snapshot: BattlerSnapshot;
  at: number;
}

export interface ActiveBattle {
  seed: number;
  mySide: "a" | "b";
  opponentId: string;
  opponentName: string;
  result: BattleResult;
  startedAt: number;
}

/** ms per battle round in the reveal animation + a beat for the verdict. */
export const BATTLE_ROUND_MS = 1600;
export const BATTLE_VERDICT_MS = 1400;

// ── Minigame: Rock-Paper-Scissors (first minigame, testing the pattern) ─────
// Unlike battles (seed-shared auto-resolve), a minigame takes real player
// input: invite → accept → each side broadcasts its move → both clients
// resolve locally from the same two moves, so outcomes always agree.
export type RpsMove = "rock" | "paper" | "scissors";

export interface MinigameInvite {
  from: string;
  fromName: string;
  at: number;
}

export interface ActiveMinigame {
  /** Server-authoritative match row id (minigame_matches.id) — generated by
   *  the accepting player and shared via the "accept" broadcast, so both
   *  clients agree on the same id with no derivation/hashing needed. See
   *  submit_minigame_result (Phase A, plan-deathDecayMinigameBalance.md). */
  matchId: string;
  opponentId: string;
  opponentName: string;
  myMove: RpsMove | null;
  theirMove: RpsMove | null;
  /** Set once both moves are in — "win"/"lose"/"tie" from MY perspective. */
  outcome: "win" | "lose" | "tie" | null;
  /** Game start on this client — drives the 5s pick countdown. */
  startedAt: number;
  /** Set the instant outcome resolves — drives the 3s reveal countdown. */
  resolvedAt: number | null;
  /** Non-null = game cancelled (someone didn't pick in time); the message. */
  cancelled: string | null;
  /** userId of whoever hit "Give up" — resolves instantly (no reveal
   *  drumroll): loss for the quitter, win for the opponent. */
  forfeitedBy: string | null;
}

/** Pick window before an RPS game cancels, and the reveal-drumroll length. */
export const RPS_PICK_TIMEOUT_MS = 5_000;
export const RPS_REVEAL_MS = 3_000;

export function rpsOutcome(mine: RpsMove, theirs: RpsMove): "win" | "lose" | "tie" {
  if (mine === theirs) return "tie";
  const beats: Record<RpsMove, RpsMove> = { rock: "scissors", paper: "rock", scissors: "paper" };
  return beats[mine] === theirs ? "win" : "lose";
}

// ── Room-wide minigame lobby + Target Toss (mg-* events) ────────────────────
// Lobby is host-authoritative pre-start (host rebroadcasts mg-roster as
// ground truth); once mg-start bakes the turn order, NO further host
// authority exists — every client derives turns/phases/winner by running
// pet-core's applyTossEvent reducer over the same ordered mg-throw/mg-skip
// log. All handlers are registered inside join()'s buildAndSubscribe — never
// open a second channel for the same pet-room topic (dedupe footgun).

export const TOSS_TURN_TIMEOUT_MS = 30_000;
/** Grace before the authority client skips a DEPARTED player's turn. */
const TOSS_DEPARTED_SKIP_MS = 3_000;

export interface LobbyInvite {
  hostId: string;
  hostName: string;
  gameCode: string;
  cap: number;
  at: number;
}

export interface MinigameLobby {
  gameCode: string;
  hostId: string;
  hostName: string;
  cap: number;
  /** Join order, host first — becomes the turn order at start. */
  accepted: { userId: string; name: string }[];
  ready: string[];
}

/** Live aim preview from the active thrower: pull displacement normalized
 *  to viewport fractions (matching the `pos` convention) so every viewer's
 *  screen shows the same relative pull-back regardless of resolution.
 *  Throttled like `pos`; cleared on release/throw/turn-change/staleness. */
export interface TossAim {
  userId: string;
  dxN: number;
  dyN: number;
  /** Local receive time — drives the staleness sweep. */
  at: number;
}
/** Min gap between aim broadcasts (drag mousemove fires far faster). */
const TOSS_AIM_SEND_MS = 90;
/** An aim with no update for this long is stale (sender lagged/vanished). */
const TOSS_AIM_STALE_MS = 800;

/** Slide replay parameters, normalized to screen fractions (like `pos`).
 *  distance null = a miss (puck slid off screen) — still a real throw
 *  event with a full visual, it just scores like a skip. */
export interface TossThrowFx {
  id: string;
  userId: string;
  toNX: number;
  toNY: number;
  duration: number;
  spinDegrees: number;
  distance: number | null;
}

export interface TargetTossState {
  /** Server-authoritative match row id — generated by the host at
   *  mg-start and shared to every client in the same broadcast as the
   *  seed/turn order, so all participants agree on one id. */
  matchId: string;
  core: TossGameCore;
  names: Record<string, string>;
  hostId: string;
  /** Shared with every client at game start — feeds arenaLayoutForTurn so
   *  everyone sees the same random target/launcher position each round. */
  seed: number;
  /** Reset on every applied event — drives the AFK countdown. */
  turnStartedAt: number;
  /** Latest throw for all clients to replay; markers accumulate per round. */
  lastFx: TossThrowFx | null;
  /** Current round's landing markers (cleared when the round advances). */
  markers: { userId: string; nx: number; ny: number; distance: number }[];
  /** phase:round key the markers belong to — new key wipes them. */
  markersKey: string;
  /** Players who hit "Give up" mid-game: their remaining turns are
   *  auto-skipped quickly, and if only one active participant remains,
   *  that player wins outright. */
  forfeited: string[];
}

// ── Chess (Phase 3) ──────────────────────────────────────────────────────────
// Untimed 1:1 games persisted in the chess_games table (group-scoped) so they
// survive restarts/room-leaves; Realtime "chess" broadcasts keep connected
// clients in live sync, the DB row is the resume-of-record. player_a = WHITE
// (the challenger), player_b = BLACK (the acceptor). Move legality is
// client-validated (chess.js); the DB enforces turn ownership on updates
// (MVP trust tradeoff, flagged in the migration).

export const CHESS_GAME_CODE = "chess";
/** Grace before a cancel proposal can resolve unilaterally against an
 *  opponent with no room presence (tunable placeholder — deliberately NOT a
 *  short timer: untimed means no urgency while both players are around). */
export const CHESS_UNREACHABLE_GRACE_MS = 48 * 3600_000;

/** One SAN move + when it was played. `at` is null for moves written before
 *  timestamps existed (old rows stored bare SAN strings — chessRowToGame
 *  normalizes both shapes to this one so the UI never type-checks a union). */
export interface ChessMoveEntry {
  san: string;
  at: string | null;
}

export interface ChessGame {
  id: string;
  groupId: string;
  /** White (the challenger). */
  playerAId: string;
  /** Black (the acceptor). */
  playerBId: string;
  fen: string;
  /** Full SAN log (normalized {san, at}) — drives the move-list widget. */
  moveHistory: ChessMoveEntry[];
  currentTurn: string;
  status: "active" | "finished" | "abandoned";
  winnerId: string | null;
  resultReason: string | null;
  updatedAt: string;
}

export interface ChessInvite {
  from: string;
  fromName: string;
  at: number;
}

interface ChessGameRow {
  id: string;
  group_id: string;
  player_a_id: string;
  player_b_id: string;
  board_fen: string;
  move_history: unknown;
  current_turn: string;
  status: "active" | "finished" | "abandoned";
  winner_id: string | null;
  result_reason: string | null;
  updated_at: string;
}

function chessRowToGame(r: ChessGameRow): ChessGame {
  return {
    id: r.id,
    groupId: r.group_id,
    playerAId: r.player_a_id,
    playerBId: r.player_b_id,
    fen: r.board_fen,
    // Backward-compatible normalize: rows written before move timestamps
    // hold bare SAN strings; newer rows hold {san, at} objects. Same jsonb
    // column, no migration — just two accepted shapes on read.
    moveHistory: Array.isArray(r.move_history)
      ? (r.move_history as unknown[]).flatMap((m): ChessMoveEntry[] => {
          if (typeof m === "string") return [{ san: m, at: null }];
          if (m && typeof m === "object" && typeof (m as { san?: unknown }).san === "string") {
            const at = (m as { at?: unknown }).at;
            return [{ san: (m as { san: string }).san, at: typeof at === "string" ? at : null }];
          }
          return [];
        })
      : [],
    currentTurn: r.current_turn,
    status: r.status,
    winnerId: r.winner_id,
    resultReason: r.result_reason,
    updatedAt: r.updated_at,
  };
}

const POS_SEND_MS = 200;
const INVITE_TTL_MS = 30_000;

export interface RoomApi {
  /** The local player's own userId (null while signed out). */
  selfId: string | null;
  activeGroup: GroupInfo | null;
  connected: boolean;
  members: RoomMember[];
  positions: Record<string, { nx: number; ny: number }>;
  bubbles: Record<string, ChatMsg>;
  emotes: Record<string, { emoji: string; at: number }>;
  chatLog: ChatMsg[];
  incomingInvite: BattleInvite | null;
  outgoingInviteTo: string | null;
  battle: ActiveBattle | null;
  incomingGameInvite: MinigameInvite | null;
  outgoingGameInviteTo: string | null;
  minigame: ActiveMinigame | null;
  lobbyInvite: LobbyInvite | null;
  minigameLobby: MinigameLobby | null;
  /** "turned away" / "host left" style lobby feedback. */
  lobbyNotice: string | null;
  tossGame: TargetTossState | null;
  /** Live pull-back preview from the active thrower (null = not aiming). */
  tossAim: TossAim | null;
  /** Broadcast my pull displacement while aiming (viewport fractions;
   *  throttled internally — safe to call from every mousemove). */
  sendTossAim: (dxN: number, dyN: number) => void;
  /** Tell viewers the pull ended (release or cancel). */
  clearTossAim: () => void;
  join: (group: GroupInfo) => void;
  leaveRoom: () => void;
  updateMyPosition: (nx: number, ny: number) => void;
  sendChat: (text: string) => void;
  sendEmote: (emoji: string) => void;
  sendSocialPet: (targetUserId: string) => void;
  challenge: (targetUserId: string) => void;
  acceptInvite: () => void;
  declineInvite: () => void;
  clearBattle: () => void;
  inviteMinigame: (targetUserId: string) => void;
  acceptGameInvite: () => void;
  declineGameInvite: () => void;
  sendRpsMove: (move: RpsMove) => void;
  clearMinigame: () => void;
  /** "Give up" (RPS): decisive — I take the loss, the opponent gets the
   *  win; both sides' onMinigameResolved fires and records normally. */
  forfeitMinigame: () => void;
  /** "Give up" (Target Toss): broadcasts the forfeit, records nothing here
   *  (the caller records the quitter's own loss) and closes my board. */
  forfeitTossGame: () => void;
  createMinigameLobby: (cap: number) => void;
  acceptLobbyInvite: () => void;
  declineLobbyInvite: () => void;
  toggleTossReady: () => void;
  startTossGame: () => void;
  cancelMinigameLobby: () => void;
  submitToss: (fx: Omit<TossThrowFx, "id" | "userId">) => void;
  dismissTossGame: () => void;
  clearLobbyNotice: () => void;
  // ── Chess ──────────────────────────────────────────────────────────────
  /** Games loaded for this room's group (active + just-ended ones still
   *  showing their result banner). */
  chessGames: ChessGame[];
  incomingChessInvite: ChessInvite | null;
  outgoingChessInviteTo: string | null;
  /** Friendly feedback ("you already have a game with them", etc.). */
  chessNotice: string | null;
  clearChessNotice: () => void;
  /** The game whose board panel is open (null = closed). */
  openChessGameId: string | null;
  /** Panel collapsed to a floating chip — game/subscription stays live. */
  chessMinimized: boolean;
  /** Pending cancel proposals per gameId (from = proposer). */
  chessCancelProposals: Record<string, { from: string; at: number }>;
  chessChallenge: (targetUserId: string) => void;
  acceptChessInvite: () => void;
  declineChessInvite: () => void;
  openChessGame: (gameId: string) => void;
  minimizeChessPanel: () => void;
  restoreChessPanel: () => void;
  closeChessPanel: () => void;
  /** Persist + broadcast one locally-validated move (and any game end the
   *  move causes — checkmate/draw — in the same update). */
  sendChessMove: (
    gameId: string,
    san: string,
    fen: string,
    end?: { winnerId: string | null; reason: "checkmate" | "draw" },
  ) => void;
  /** "Give up": decisive — my loss, opponent's win. */
  resignChess: (gameId: string) => void;
  /** Propose a no-score-impact mutual cancel to the opponent. */
  proposeChessCancel: (gameId: string) => void;
  /** Respond to an incoming cancel proposal. */
  respondChessCancel: (gameId: string, accept: boolean) => void;
  /** Unreachable-opponent escape hatch (no score impact) — UI gates this on
   *  the opponent being absent + no game activity for the grace period. */
  cancelChessUnreachable: (gameId: string) => void;
}

interface UseRoomOptions {
  userId: string | null;
  displayName: string;
  save: PetSaveData;
  /** Egg-phase pets cannot go online (product rule). */
  isEgg: boolean;
  onSocialPet: (fromName: string) => void;
  onBattleResolved: (won: boolean, opponentName: string) => void;
  onMinigameResolved: (
    outcome: "win" | "lose" | "tie",
    opponentName: string,
    matchId: string,
    myMove: RpsMove,
  ) => void;
  /** A chess game I play in reached a DECISIVE end (checkmate/resignation)
   *  or a draw — outcome is from MY perspective. Fires exactly once per
   *  game per session; the callback owns result recording/history. Never
   *  fires for abandoned (cancelled) games — those have no score impact. */
  onChessResolved: (outcome: "win" | "lose" | "tie", opponentName: string) => void;
}

function snapshotOf(save: PetSaveData): BattlerSnapshot {
  return {
    name: save.name,
    stage: save.evolutionStage,
    hunger: save.hunger,
    cleanliness: save.cleanliness,
    happiness: save.happiness,
  };
}

export function useRoom({
  userId,
  displayName,
  save,
  isEgg,
  onSocialPet,
  onBattleResolved,
  onMinigameResolved,
  onChessResolved,
}: UseRoomOptions): RoomApi {
  const [activeGroup, setActiveGroup] = useState<GroupInfo | null>(null);
  const [connected, setConnected] = useState(false);
  const [members, setMembers] = useState<RoomMember[]>([]);
  const [positions, setPositions] = useState<Record<string, { nx: number; ny: number }>>({});
  const [bubbles, setBubbles] = useState<Record<string, ChatMsg>>({});
  const [emotes, setEmotes] = useState<Record<string, { emoji: string; at: number }>>({});
  const [chatLog, setChatLog] = useState<ChatMsg[]>([]);
  const [incomingInvite, setIncomingInvite] = useState<BattleInvite | null>(null);
  const [outgoingInviteTo, setOutgoingInviteTo] = useState<string | null>(null);
  const [battle, setBattle] = useState<ActiveBattle | null>(null);
  const [incomingGameInvite, setIncomingGameInvite] = useState<MinigameInvite | null>(null);
  const [outgoingGameInviteTo, setOutgoingGameInviteTo] = useState<string | null>(null);
  const [minigame, setMinigame] = useState<ActiveMinigame | null>(null);
  const [lobbyInvite, setLobbyInvite] = useState<LobbyInvite | null>(null);
  const [minigameLobby, setMinigameLobby] = useState<MinigameLobby | null>(null);
  const [lobbyNotice, setLobbyNotice] = useState<string | null>(null);
  const [tossGame, setTossGame] = useState<TargetTossState | null>(null);
  const [tossAim, setTossAim] = useState<TossAim | null>(null);
  const lastAimSentAtRef = useRef(0);
  // ── Chess state ──────────────────────────────────────────────────────────
  const [chessGames, setChessGames] = useState<ChessGame[]>([]);
  const [incomingChessInvite, setIncomingChessInvite] = useState<ChessInvite | null>(null);
  const [outgoingChessInviteTo, setOutgoingChessInviteTo] = useState<string | null>(null);
  const [chessNotice, setChessNotice] = useState<string | null>(null);
  const [openChessGameId, setOpenChessGameId] = useState<string | null>(null);
  const [chessMinimized, setChessMinimized] = useState(false);
  const [chessCancelProposals, setChessCancelProposals] = useState<Record<string, { from: string; at: number }>>({});
  const chessGamesRef = useRef<ChessGame[]>([]);
  chessGamesRef.current = chessGames;
  /** Game ids whose decisive end was already reported to onChessResolved. */
  const chessRecordedRef = useRef<Set<string>>(new Set());
  // Ref mirrors for the broadcast handlers (registered once per join, so
  // they can't close over fresh state).
  const lobbyRef = useRef<MinigameLobby | null>(null);
  lobbyRef.current = minigameLobby;
  const tossRef = useRef<TargetTossState | null>(null);
  tossRef.current = tossGame;
  const sentLobbyJoinRef = useRef(false);

  const channelRef = useRef<RealtimeChannel | null>(null);
  const saveRef = useRef(save);
  saveRef.current = save;
  const nameRef = useRef(displayName);
  nameRef.current = displayName;
  const myPosRef = useRef<{ nx: number; ny: number } | null>(null);
  const lastSentPosRef = useRef<{ nx: number; ny: number } | null>(null);
  const outgoingSnapshotRef = useRef<BattlerSnapshot | null>(null);
  const battleRewardTimer = useRef<ReturnType<typeof setTimeout> | undefined>(undefined);
  const onSocialPetRef = useRef(onSocialPet);
  onSocialPetRef.current = onSocialPet;
  const onBattleResolvedRef = useRef(onBattleResolved);
  onBattleResolvedRef.current = onBattleResolved;
  const onMinigameResolvedRef = useRef(onMinigameResolved);
  onMinigameResolvedRef.current = onMinigameResolved;
  const onChessResolvedRef = useRef(onChessResolved);
  onChessResolvedRef.current = onChessResolved;

  // Bumped on every teardown/join so an async-deferred channel build (see
  // join's stale-topic path) can detect it's been superseded and bail —
  // otherwise leaving the room during that window would let the late
  // buildAndSubscribe create a ghost presence in a room the UI already left.
  const joinGenRef = useRef(0);

  const teardown = useCallback(() => {
    joinGenRef.current++;
    if (channelRef.current && supabase) {
      void supabase.removeChannel(channelRef.current);
    }
    channelRef.current = null;
    setActiveGroup(null);
    setConnected(false);
    setMembers([]);
    setPositions({});
    setBubbles({});
    setEmotes({});
    setChatLog([]);
    setIncomingInvite(null);
    setOutgoingInviteTo(null);
    setBattle(null);
    setIncomingGameInvite(null);
    setOutgoingGameInviteTo(null);
    setMinigame(null);
    setLobbyInvite(null);
    setMinigameLobby(null);
    setLobbyNotice(null);
    setTossGame(null);
    setTossAim(null);
    sentLobbyJoinRef.current = false;
    // Chess: leaving the ROOM never resolves a game (it lives in the DB and
    // resumes on rejoin) — only the local panel/list state clears here.
    setChessGames([]);
    setIncomingChessInvite(null);
    setOutgoingChessInviteTo(null);
    setOpenChessGameId(null);
    setChessMinimized(false);
    setChessCancelProposals({});
    if (battleRewardTimer.current) clearTimeout(battleRewardTimer.current);
  }, []);

  useEffect(() => teardown, [teardown]);

  /** Applies one Target Toss throw/skip to local game state (own or remote).
   *  Declared before join() — its broadcast handler closes over this. */
  const applyToss = useCallback(
    (ev: { userId: string; distance: number | null; seq: number }, fx: TossThrowFx | null) => {
      setTossGame((prev) => {
        if (!prev) return prev;
        // Dedupe/order guard: every event carries the sender's seq; anything
        // that doesn't extend our log exactly is a duplicate or stale.
        if (ev.seq !== prev.core.seq) return prev;
        const turn = currentTossTurn(prev.core);
        if (!turn || turn.userId !== ev.userId) return prev;
        const evKey = `${turn.phase}:${turn.round}`;
        const core = applyTossEvent(prev.core, { userId: ev.userId, distance: ev.distance });
        const keep = prev.markersKey === evKey ? prev.markers : [];
        // Misses (distance null — puck slid off screen) leave no marker.
        const markers =
          fx && fx.distance !== null
            ? [...keep, { userId: ev.userId, nx: fx.toNX, ny: fx.toNY, distance: fx.distance }]
            : keep;
        return {
          ...prev,
          core,
          markers,
          markersKey: evKey,
          lastFx: fx ?? prev.lastFx,
          turnStartedAt: Date.now(),
        };
      });
      // A resolved turn always ends that player's aim preview (covers both
      // the throw itself and an authority skip).
      setTossAim((prev) => (prev?.userId === ev.userId ? null : prev));
    },
    [],
  );

  /** (Re)loads this group's active chess games from the DB — the
   *  resume-of-record (broadcasts only keep LIVE clients in sync). */
  const loadChessGames = useCallback(async (groupId: string) => {
    if (!supabase) return;
    const { data, error } = await supabase
      .from("chess_games")
      .select("*")
      .eq("group_id", groupId)
      .eq("status", "active");
    if (error) {
      console.error("[chess] load failed:", error);
      return;
    }
    const loaded = ((data ?? []) as ChessGameRow[]).map(chessRowToGame);
    // Active list is replaced by DB truth; keep local just-ended games whose
    // result banner is still on screen.
    setChessGames((prev) => {
      const ended = prev.filter((g) => g.status !== "active" && !loaded.some((l) => l.id === g.id));
      return [...loaded, ...ended];
    });
  }, []);

  /** Starts (or schedules) the local battle replay once both sides agree. */
  const beginBattle = useCallback(
    (seed: number, mySide: "a" | "b", a: BattlerSnapshot, b: BattlerSnapshot, opponentId: string, opponentName: string) => {
      const result = resolveBattle(seed, a, b);
      const startedAt = Date.now();
      setBattle({ seed, mySide, opponentId, opponentName, result, startedAt });
      setIncomingInvite(null);
      setOutgoingInviteTo(null);
      const total = result.rounds.length * BATTLE_ROUND_MS + BATTLE_VERDICT_MS;
      if (battleRewardTimer.current) clearTimeout(battleRewardTimer.current);
      battleRewardTimer.current = setTimeout(() => {
        onBattleResolvedRef.current(result.winner === mySide, opponentName);
      }, total);
    },
    [],
  );

  const join = useCallback(
    (group: GroupInfo) => {
      if (!supabase || !userId || isEgg) return;
      teardown();
      // supabase.channel(topic) dedupes by topic: if the groups menu has a
      // read-only presence observer open on this room (SideDock's
      // useGroupPresenceCount), channel() would hand us THAT already-
      // subscribed instance (wrong presence key, subscribe() would throw).
      // Free the topic first and only build our channel once it's gone.
      const topic = `realtime:pet-room:${group.id}`;
      const stale = supabase.getChannels().find((c) => c.topic === topic);
      const buildAndSubscribe = () => {
        const channel = supabase!.channel(`pet-room:${group.id}`, {
          config: { presence: { key: userId }, broadcast: { self: false } },
        });
        channelRef.current = channel;

        channel.on("presence", { event: "sync" }, () => {
          const state = channel.presenceState<RoomMember>();
          const roster: RoomMember[] = [];
          for (const key of Object.keys(state)) {
            const entry = state[key]?.[0];
            if (entry && key !== userId) roster.push(entry);
          }
          setMembers(roster);
          // Drop stale per-user artifacts for anyone who left.
          setPositions((prev) => {
            const next: typeof prev = {};
            for (const m of roster) if (prev[m.userId]) next[m.userId] = prev[m.userId]!;
            return next;
          });
        });

        channel.on("broadcast", { event: "pos" }, ({ payload }) => {
          const p = payload as { from: string; nx: number; ny: number };
          setPositions((prev) => ({ ...prev, [p.from]: { nx: p.nx, ny: p.ny } }));
        });

        channel.on("broadcast", { event: "chat" }, ({ payload }) => {
          const msg = payload as ChatMsg;
          setChatLog((prev) => [...prev.slice(-49), msg]);
          setBubbles((prev) => ({ ...prev, [msg.from]: msg }));
        });

        channel.on("broadcast", { event: "emote" }, ({ payload }) => {
          const p = payload as { from: string; emoji: string };
          setEmotes((prev) => ({ ...prev, [p.from]: { emoji: p.emoji, at: Date.now() } }));
        });

        channel.on("broadcast", { event: "social-pet" }, ({ payload }) => {
          const p = payload as { from: string; fromName: string; to: string };
          if (p.to === userId) onSocialPetRef.current(p.fromName);
        });

        channel.on("broadcast", { event: "battle" }, ({ payload }) => {
          const p = payload as {
            kind: "challenge" | "accept" | "decline";
            from: string;
            fromName: string;
            to: string;
            seed: number;
            snapshot?: BattlerSnapshot;
          };
          if (p.to !== userId) return;
          if (p.kind === "challenge" && p.snapshot) {
            setIncomingInvite({ from: p.from, fromName: p.fromName, seed: p.seed, snapshot: p.snapshot, at: Date.now() });
          } else if (p.kind === "accept" && p.snapshot) {
            // I challenged (side "a", with the snapshot I sent); they accepted with theirs.
            const mine = outgoingSnapshotRef.current ?? snapshotOf(saveRef.current);
            beginBattle(p.seed, "a", mine, p.snapshot, p.from, p.fromName);
          } else if (p.kind === "decline") {
            setOutgoingInviteTo(null);
          }
        });

        // Room-wide minigame lobby + Target Toss event log. One "mg" event
        // with a kind discriminator (functionally the plan's mg-* events).
        channel.on("broadcast", { event: "mg" }, ({ payload }) => {
          const p = payload as {
            kind: "invite" | "join" | "ready" | "roster" | "start" | "throw" | "skip" | "cancel" | "forfeit" | "aim";
            from: string;
            fromName?: string;
            gameCode?: string;
            cap?: number;
            accepted?: { userId: string; name: string }[];
            ready?: string[];
            order?: string[];
            names?: Record<string, string>;
            seed?: number;
            seq?: number;
            target?: string;
            toNX?: number;
            toNY?: number;
            duration?: number;
            spinDegrees?: number;
            distance?: number | null;
            id?: string;
            dxN?: number;
            dyN?: number;
            released?: boolean;
            matchId?: string;
          };
          if (!userId || p.from === userId) return;

          if (p.kind === "invite") {
            // Room-wide popup — unless I'm already in a lobby/game.
            if (lobbyRef.current || tossRef.current) return;
            setLobbyInvite({
              hostId: p.from,
              hostName: p.fromName ?? "?",
              gameCode: p.gameCode ?? TARGET_TOSS_GAME_CODE,
              cap: p.cap ?? 4,
              at: Date.now(),
            });
            return;
          }

          if (p.kind === "join" || p.kind === "ready") {
            // Host-authoritative: only the host mutates the roster, then
            // rebroadcasts it as ground truth (mirrors the plan's mg-roster).
            const lobby = lobbyRef.current;
            if (!lobby || lobby.hostId !== userId || tossRef.current) return;
            let next = lobby;
            if (p.kind === "join") {
              if (!lobby.accepted.some((a) => a.userId === p.from) && lobby.accepted.length < lobby.cap) {
                next = { ...lobby, accepted: [...lobby.accepted, { userId: p.from, name: p.fromName ?? "?" }] };
              }
            } else {
              const isReady = lobby.ready.includes(p.from);
              const inLobby = lobby.accepted.some((a) => a.userId === p.from);
              if (inLobby) {
                next = { ...lobby, ready: isReady ? lobby.ready.filter((r) => r !== p.from) : [...lobby.ready, p.from] };
              }
            }
            lobbyRef.current = next;
            setMinigameLobby(next);
            // Rebroadcast even when unchanged (e.g. a join past the cap) so
            // the joiner sees a roster without themselves = turned away.
            void channel.send({
              type: "broadcast",
              event: "mg",
              payload: {
                kind: "roster",
                from: userId,
                gameCode: next.gameCode,
                cap: next.cap,
                accepted: next.accepted,
                ready: next.ready,
                hostName: next.hostName,
              },
            });
            return;
          }

          if (p.kind === "roster") {
            const accepted = p.accepted ?? [];
            const amIn = accepted.some((a) => a.userId === userId);
            if (amIn) {
              const lobby: MinigameLobby = {
                gameCode: p.gameCode ?? TARGET_TOSS_GAME_CODE,
                hostId: p.from,
                hostName: (p as { hostName?: string }).hostName ?? "?",
                cap: p.cap ?? accepted.length,
                accepted,
                ready: p.ready ?? [],
              };
              lobbyRef.current = lobby;
              setMinigameLobby(lobby);
              setLobbyInvite(null);
              sentLobbyJoinRef.current = false;
            } else if (sentLobbyJoinRef.current) {
              // I asked to join and the authoritative roster excludes me.
              sentLobbyJoinRef.current = false;
              setLobbyInvite(null);
              setLobbyNotice("That game is full — maybe next round!");
            }
            return;
          }

          if (p.kind === "start") {
            const order = p.order ?? [];
            setLobbyInvite(null);
            lobbyRef.current = null;
            setMinigameLobby(null);
            if (!order.includes(userId)) return; // spectators just drop the popup
            const matchId = p.matchId ?? crypto.randomUUID();
            setTossGame({
              matchId,
              core: initTossGame(order),
              names: p.names ?? {},
              hostId: p.from,
              seed: p.seed ?? 0,
              turnStartedAt: Date.now(),
              lastFx: null,
              markers: [],
              markersKey: "main:1",
              forfeited: [],
            });
            createMinigameMatch(matchId, "target_toss", order);
            return;
          }

          if (p.kind === "throw") {
            // distance: null is a MISS, a meaningful value — never `?? 0` it
            // (that would score an off-screen puck as a literal bullseye).
            const distance = typeof p.distance === "number" ? p.distance : null;
            applyToss(
              { userId: p.from, distance, seq: p.seq ?? -1 },
              {
                id: p.id ?? `${p.from}-${Date.now()}`,
                userId: p.from,
                toNX: p.toNX ?? 0.5,
                toNY: p.toNY ?? 0.5,
                duration: p.duration ?? 0.8,
                spinDegrees: p.spinDegrees ?? 360,
                distance,
              },
            );
            return;
          }

          if (p.kind === "skip") {
            if (p.target) applyToss({ userId: p.target, distance: null, seq: p.seq ?? -1 }, null);
            return;
          }

          if (p.kind === "aim") {
            // Live pull preview from the active thrower — display-only state
            // (never touches the reducer/event log; no seq guard needed —
            // last-write-wins is exactly right for a preview).
            if (p.released === true) {
              setTossAim((prev) => (prev?.userId === p.from ? null : prev));
              return;
            }
            setTossAim({
              userId: p.from,
              dxN: typeof p.dxN === "number" ? p.dxN : 0,
              dyN: typeof p.dyN === "number" ? p.dyN : 0,
              at: Date.now(),
            });
            return;
          }

          if (p.kind === "forfeit") {
            // A participant gave up mid-game: they're out of contention.
            // Their remaining turns get fast-skipped (see the AFK effect),
            // and the solo-remaining-player effect resolves an outright win.
            setTossGame((prev) =>
              prev && prev.core.order.includes(p.from) && !prev.forfeited.includes(p.from)
                ? { ...prev, forfeited: [...prev.forfeited, p.from] }
                : prev,
            );
            return;
          }

          if (p.kind === "cancel") {
            if (lobbyRef.current?.hostId === p.from) {
              lobbyRef.current = null;
              setMinigameLobby(null);
            }
            setLobbyInvite((inv) => (inv?.hostId === p.from ? null : inv));
          }
        });

        channel.on("broadcast", { event: "minigame" }, ({ payload }) => {
          const p = payload as {
            kind: "invite" | "accept" | "decline" | "move" | "forfeit";
            from: string;
            fromName: string;
            to: string;
            move?: RpsMove;
            matchId?: string;
          };
          if (p.to !== userId) return;
          if (p.kind === "invite") {
            setIncomingGameInvite({ from: p.from, fromName: p.fromName, at: Date.now() });
          } else if (p.kind === "accept") {
            setOutgoingGameInviteTo(null);
            // The acceptor generated this id and included it in the
            // broadcast — both clients now agree on the same match.
            const matchId = p.matchId ?? crypto.randomUUID();
            setMinigame({
              matchId,
              opponentId: p.from,
              opponentName: p.fromName,
              myMove: null,
              theirMove: null,
              outcome: null,
              startedAt: Date.now(),
              resolvedAt: null,
              cancelled: null,
              forfeitedBy: null,
            });
            if (userId) createMinigameMatch(matchId, "rps", [userId, p.from]);
          } else if (p.kind === "decline") {
            setOutgoingGameInviteTo(null);
          } else if (p.kind === "move" && p.move) {
            setMinigame((prev) => {
              if (!prev || prev.opponentId !== p.from || prev.outcome || prev.cancelled) return prev;
              const next = { ...prev, theirMove: p.move! };
              return next.myMove
                ? { ...next, outcome: rpsOutcome(next.myMove, next.theirMove!), resolvedAt: Date.now() }
                : next;
            });
          } else if (p.kind === "forfeit") {
            // Opponent gave up — decisive win for me, resolved instantly
            // (no reveal drumroll for a forfeit).
            setMinigame((prev) => {
              if (!prev || prev.opponentId !== p.from || prev.outcome || prev.cancelled) return prev;
              return { ...prev, outcome: "win", resolvedAt: Date.now(), forfeitedBy: p.from };
            });
          }
        });

        // ── Chess broadcasts (live sync; the DB row is the resume truth) ──
        channel.on("broadcast", { event: "chess" }, ({ payload }) => {
          const p = payload as {
            kind:
              | "invite"
              | "accept"
              | "decline"
              | "start"
              | "move"
              | "end"
              | "cancel-propose"
              | "cancel-decline";
            from: string;
            fromName?: string;
            to?: string;
            gameId?: string;
            san?: string;
            at?: string;
            fen?: string;
            ply?: number;
            status?: "finished" | "abandoned";
            winnerId?: string | null;
            reason?: string;
          };
          if (!userId || p.from === userId) return;

          if (p.kind === "invite") {
            if (p.to !== userId) return;
            setIncomingChessInvite({ from: p.from, fromName: p.fromName ?? "?", at: Date.now() });
            return;
          }
          if (p.kind === "decline") {
            if (p.to !== userId) return;
            setOutgoingChessInviteTo(null);
            setChessNotice(`${p.fromName ?? "They"} declined the chess challenge.`);
            return;
          }
          if (p.kind === "accept") {
            if (p.to !== userId) return;
            // I challenged (I'm white/player_a); they accepted → I create
            // the DB row, then announce it so everyone (acceptor +
            // spectators) picks it up.
            setOutgoingChessInviteTo(null);
            void (async () => {
              if (!supabase || !channelRef.current) return;
              const { data, error } = await supabase
                .from("chess_games")
                .insert({
                  group_id: group.id,
                  player_a_id: userId,
                  player_b_id: p.from,
                  current_turn: userId,
                })
                .select("*")
                .single();
              if (error) {
                // 23505 = the one-active-game-per-pair partial unique index.
                setChessNotice(
                  error.code === "23505"
                    ? "You already have an active game with them — finish or cancel it first."
                    : `Couldn't start the game: ${error.message}`,
                );
                return;
              }
              const game = chessRowToGame(data as ChessGameRow);
              setChessGames((prev) => [game, ...prev.filter((g) => g.id !== game.id)]);
              setOpenChessGameId(game.id);
              setChessMinimized(false);
              void channelRef.current.send({
                type: "broadcast",
                event: "chess",
                payload: { kind: "start", from: userId, gameId: game.id },
              });
            })();
            return;
          }
          if (p.kind === "start" && p.gameId) {
            // A new game exists — fetch its row (spectators too); the
            // acceptor also opens their board.
            void (async () => {
              if (!supabase) return;
              const { data } = await supabase.from("chess_games").select("*").eq("id", p.gameId).maybeSingle();
              if (!data) return;
              const g = chessRowToGame(data as ChessGameRow);
              setChessGames((prev) => [g, ...prev.filter((x) => x.id !== g.id)]);
              if (g.playerAId === userId || g.playerBId === userId) {
                setOpenChessGameId(g.id);
                setChessMinimized(false);
                setIncomingChessInvite(null);
              }
            })();
            return;
          }
          if (p.kind === "move" && p.gameId && p.san && p.fen) {
            setChessGames((prev) =>
              prev.map((g) => {
                if (g.id !== p.gameId || g.status !== "active") return g;
                // ply = history length AFTER the move — apply only if it
                // extends ours exactly (drops dupes/stale echoes; a real
                // gap self-heals on the next DB load).
                if (typeof p.ply === "number" && p.ply !== g.moveHistory.length + 1) return g;
                const nextTurn = g.currentTurn === g.playerAId ? g.playerBId : g.playerAId;
                return {
                  ...g,
                  fen: p.fen!,
                  moveHistory: [...g.moveHistory, { san: p.san!, at: p.at ?? null }],
                  currentTurn: nextTurn,
                  status: p.status ?? "active",
                  winnerId: p.status ? (p.winnerId ?? null) : g.winnerId,
                  resultReason: p.status ? (p.reason ?? null) : g.resultReason,
                  updatedAt: new Date().toISOString(),
                };
              }),
            );
            return;
          }
          if (p.kind === "end" && p.gameId && p.status) {
            setChessGames((prev) =>
              prev.map((g) =>
                g.id === p.gameId && g.status === "active"
                  ? {
                      ...g,
                      status: p.status!,
                      winnerId: p.winnerId ?? null,
                      resultReason: p.reason ?? null,
                      updatedAt: new Date().toISOString(),
                    }
                  : g,
              ),
            );
            setChessCancelProposals((prev) => {
              if (!(p.gameId! in prev)) return prev;
              const next = { ...prev };
              delete next[p.gameId!];
              return next;
            });
            return;
          }
          if (p.kind === "cancel-propose" && p.gameId) {
            if (p.to !== userId) return;
            setChessCancelProposals((prev) => ({ ...prev, [p.gameId!]: { from: p.from, at: Date.now() } }));
            return;
          }
          if (p.kind === "cancel-decline" && p.gameId) {
            if (p.to !== userId) return;
            setChessNotice("Your cancel proposal was declined — the game continues.");
          }
        });

        channel.subscribe((status) => {
          if (status === "SUBSCRIBED") {
            setConnected(true);
            void loadChessGames(group.id);
            const s = saveRef.current;
            void channel.track({
              userId,
              name: nameRef.current,
              petName: s.name,
              petType: s.petType,
              stage: s.evolutionStage,
            } satisfies RoomMember);
          } else if (status === "CHANNEL_ERROR" || status === "TIMED_OUT" || status === "CLOSED") {
            setConnected(false);
          }
        });
      };
      // setActiveGroup runs immediately (not inside buildAndSubscribe) so the
      // UI flips to "in room" without waiting on the stale-channel removal.
      setActiveGroup(group);
      if (stale) {
        // Deferred build: bail if a teardown/re-join superseded this join
        // while the stale observer channel was being removed — a late
        // buildAndSubscribe would otherwise track ghost presence in a room
        // the UI already left.
        const gen = joinGenRef.current;
        void supabase.removeChannel(stale).then(() => {
          if (joinGenRef.current === gen) buildAndSubscribe();
        });
      } else {
        buildAndSubscribe();
      }
    },
    [userId, isEgg, teardown, beginBattle, applyToss, loadChessGames],
  );

  // Position publisher: GameView pushes the local pet's normalized position
  // into myPosRef; this interval broadcasts it at ≤5Hz, only when it moved.
  const updateMyPosition = useCallback((nx: number, ny: number) => {
    myPosRef.current = { nx, ny };
  }, []);

  useEffect(() => {
    if (!activeGroup || !connected || !userId) return;
    const id = setInterval(() => {
      const pos = myPosRef.current;
      const last = lastSentPosRef.current;
      if (!pos || !channelRef.current) return;
      if (last && Math.abs(last.nx - pos.nx) < 0.004 && Math.abs(last.ny - pos.ny) < 0.004) return;
      lastSentPosRef.current = pos;
      void channelRef.current.send({
        type: "broadcast",
        event: "pos",
        payload: { from: userId, nx: pos.nx, ny: pos.ny },
      });
    }, POS_SEND_MS);
    return () => clearInterval(id);
  }, [activeGroup, connected, userId]);

  // Housekeeping: expire bubbles (6s), emotes (3s) and stale invites (30s).
  useEffect(() => {
    if (!activeGroup) return;
    const id = setInterval(() => {
      const now = Date.now();
      setBubbles((prev) => {
        const next: typeof prev = {};
        let changed = false;
        for (const k of Object.keys(prev)) {
          if (now - prev[k]!.at < 6000) next[k] = prev[k]!;
          else changed = true;
        }
        return changed ? next : prev;
      });
      setEmotes((prev) => {
        const next: typeof prev = {};
        let changed = false;
        for (const k of Object.keys(prev)) {
          if (now - prev[k]!.at < 3000) next[k] = prev[k]!;
          else changed = true;
        }
        return changed ? next : prev;
      });
      setIncomingInvite((inv) => (inv && now - inv.at > INVITE_TTL_MS ? null : inv));
      setIncomingGameInvite((inv) => (inv && now - inv.at > INVITE_TTL_MS ? null : inv));
      setIncomingChessInvite((inv) => (inv && now - inv.at > INVITE_TTL_MS ? null : inv));
      // A pull preview with no fresh update is stale (sender lagged out or
      // the release broadcast was lost) — drop it rather than freeze it.
      setTossAim((prev) => (prev && now - prev.at > TOSS_AIM_STALE_MS ? null : prev));
    }, 1000);
    return () => clearInterval(id);
  }, [activeGroup]);

  const sendChat = useCallback(
    (text: string) => {
      const trimmed = text.trim();
      if (!trimmed || !channelRef.current || !userId) return;
      const msg: ChatMsg = {
        id: `${userId}-${Date.now()}`,
        from: userId,
        name: nameRef.current,
        text: trimmed.slice(0, 200),
        at: Date.now(),
      };
      // broadcast self:false — apply locally too so my own bubble/log shows.
      setChatLog((prev) => [...prev.slice(-49), msg]);
      setBubbles((prev) => ({ ...prev, [userId]: msg }));
      void channelRef.current.send({ type: "broadcast", event: "chat", payload: msg });
    },
    [userId],
  );

  const sendEmote = useCallback(
    (emoji: string) => {
      if (!channelRef.current || !userId) return;
      setEmotes((prev) => ({ ...prev, [userId]: { emoji, at: Date.now() } }));
      void channelRef.current.send({ type: "broadcast", event: "emote", payload: { from: userId, emoji } });
    },
    [userId],
  );

  const sendSocialPet = useCallback(
    (targetUserId: string) => {
      if (!channelRef.current || !userId) return;
      void channelRef.current.send({
        type: "broadcast",
        event: "social-pet",
        payload: { from: userId, fromName: nameRef.current, to: targetUserId },
      });
    },
    [userId],
  );

  const challenge = useCallback(
    (targetUserId: string) => {
      if (!channelRef.current || !userId || battle) return;
      const snapshot = snapshotOf(saveRef.current);
      outgoingSnapshotRef.current = snapshot;
      setOutgoingInviteTo(targetUserId);
      void channelRef.current.send({
        type: "broadcast",
        event: "battle",
        payload: {
          kind: "challenge",
          from: userId,
          fromName: nameRef.current,
          to: targetUserId,
          seed: Math.floor(Math.random() * 2_147_483_647),
          snapshot,
        },
      });
    },
    [userId, battle],
  );

  const acceptInvite = useCallback(() => {
    const inv = incomingInvite;
    if (!inv || !channelRef.current || !userId) return;
    const mine = snapshotOf(saveRef.current);
    void channelRef.current.send({
      type: "broadcast",
      event: "battle",
      payload: { kind: "accept", from: userId, fromName: nameRef.current, to: inv.from, seed: inv.seed, snapshot: mine },
    });
    // Challenger is always side "a"; I accepted, so I'm "b".
    beginBattle(inv.seed, "b", inv.snapshot, mine, inv.from, inv.fromName);
  }, [incomingInvite, userId, beginBattle]);

  const declineInvite = useCallback(() => {
    const inv = incomingInvite;
    if (!inv || !channelRef.current || !userId) return;
    void channelRef.current.send({
      type: "broadcast",
      event: "battle",
      payload: { kind: "decline", from: userId, fromName: nameRef.current, to: inv.from, seed: inv.seed },
    });
    setIncomingInvite(null);
  }, [incomingInvite, userId]);

  const clearBattle = useCallback(() => setBattle(null), []);

  // Server-authoritative match creation (Phase A,
  // plan-deathDecayMinigameBalance.md) — every participant calls this once
  // with the SAME client-agreed matchId (idempotent: on conflict do nothing,
  // whoever's insert lands first wins, and all callers pass the same
  // participant set anyway). Fire-and-forget: submit_minigame_result raises
  // its own clear error if a match somehow never got created, and minigame
  // score-recording failures already only ever log via dbg-equivalent
  // console warnings in GameView, never block gameplay.
  const createMinigameMatch = useCallback(
    (matchId: string, gameCode: "rps" | "target_toss", participantIds: string[]) => {
      if (!supabase) return;
      void supabase
        .rpc("create_minigame_match", {
          p_match_id: matchId,
          p_game_code: gameCode,
          p_participant_ids: participantIds,
        })
        .then(({ error }) => {
          if (error) console.warn(`[room] create_minigame_match failed: ${error.message}`);
        });
    },
    [],
  );

  // ── Minigame verbs ────────────────────────────────────────────────────────
  const inviteMinigame = useCallback(
    (targetUserId: string) => {
      // One game at a time: no RPS while a Target Toss lobby/game is live
      // (mirrors createMinigameLobby's guard in the other direction).
      if (!channelRef.current || !userId || minigame || lobbyRef.current || tossRef.current) return;
      setOutgoingGameInviteTo(targetUserId);
      void channelRef.current.send({
        type: "broadcast",
        event: "minigame",
        payload: { kind: "invite", from: userId, fromName: nameRef.current, to: targetUserId },
      });
    },
    [userId, minigame],
  );

  const acceptGameInvite = useCallback(() => {
    const inv = incomingGameInvite;
    if (!inv || !channelRef.current || !userId) return;
    // I'm the acceptor — I mint the shared match id and hand it to the
    // challenger in the same broadcast, so both clients agree on one id
    // with no derivation/hashing needed.
    const matchId = crypto.randomUUID();
    void channelRef.current.send({
      type: "broadcast",
      event: "minigame",
      payload: { kind: "accept", from: userId, fromName: nameRef.current, to: inv.from, matchId },
    });
    setMinigame({
      matchId,
      opponentId: inv.from,
      opponentName: inv.fromName,
      myMove: null,
      theirMove: null,
      outcome: null,
      startedAt: Date.now(),
      resolvedAt: null,
      cancelled: null,
      forfeitedBy: null,
    });
    createMinigameMatch(matchId, "rps", [userId, inv.from]);
    setIncomingGameInvite(null);
  }, [incomingGameInvite, userId, createMinigameMatch]);

  const declineGameInvite = useCallback(() => {
    const inv = incomingGameInvite;
    if (!inv || !channelRef.current || !userId) return;
    void channelRef.current.send({
      type: "broadcast",
      event: "minigame",
      payload: { kind: "decline", from: userId, fromName: nameRef.current, to: inv.from },
    });
    setIncomingGameInvite(null);
  }, [incomingGameInvite, userId]);

  const sendRpsMove = useCallback(
    (move: RpsMove) => {
      if (!channelRef.current || !userId) return;
      setMinigame((prev) => {
        if (!prev || prev.myMove || prev.outcome || prev.cancelled) return prev;
        const next = { ...prev, myMove: move };
        return next.theirMove
          ? { ...next, outcome: rpsOutcome(move, next.theirMove), resolvedAt: Date.now() }
          : next;
      });
      void channelRef.current.send({
        type: "broadcast",
        event: "minigame",
        payload: { kind: "move", from: userId, fromName: nameRef.current, to: minigame?.opponentId, move },
      });
    },
    [userId, minigame],
  );

  const clearMinigame = useCallback(() => setMinigame(null), []);

  // "Give up" (RPS): always decisive — I take the loss, the opponent gets
  // the win. Setting outcome fires the normal onMinigameResolved path on
  // BOTH clients, so results/history record exactly like a played-out game.
  const forfeitMinigame = useCallback(() => {
    const g = minigame;
    if (!g || g.outcome || g.cancelled || !channelRef.current || !userId) return;
    void channelRef.current.send({
      type: "broadcast",
      event: "minigame",
      payload: { kind: "forfeit", from: userId, fromName: nameRef.current, to: g.opponentId },
    });
    setMinigame((prev) =>
      prev && !prev.outcome && !prev.cancelled
        ? { ...prev, outcome: "lose", resolvedAt: Date.now(), forfeitedBy: userId }
        : prev,
    );
  }, [userId, minigame]);

  // ── Target Toss lobby + game verbs ───────────────────────────────────────
  const sendMg = useCallback((payload: Record<string, unknown>) => {
    if (!channelRef.current) return;
    void channelRef.current.send({ type: "broadcast", event: "mg", payload });
  }, []);

  const createMinigameLobby = useCallback(
    (cap: number) => {
      if (!channelRef.current || !userId || lobbyRef.current || tossRef.current || minigame) return;
      const lobby: MinigameLobby = {
        gameCode: TARGET_TOSS_GAME_CODE,
        hostId: userId,
        hostName: nameRef.current,
        cap: Math.max(2, cap),
        accepted: [{ userId, name: nameRef.current }],
        ready: [userId], // host is implicitly ready
      };
      lobbyRef.current = lobby;
      setMinigameLobby(lobby);
      setLobbyNotice(null);
      sendMg({ kind: "invite", from: userId, fromName: nameRef.current, gameCode: lobby.gameCode, cap: lobby.cap });
    },
    [userId, minigame, sendMg],
  );

  const acceptLobbyInvite = useCallback(() => {
    const inv = lobbyInvite;
    if (!inv || !channelRef.current || !userId) return;
    sentLobbyJoinRef.current = true;
    sendMg({ kind: "join", from: userId, fromName: nameRef.current });
  }, [lobbyInvite, userId, sendMg]);

  const declineLobbyInvite = useCallback(() => setLobbyInvite(null), []);

  const toggleTossReady = useCallback(() => {
    const lobby = lobbyRef.current;
    if (!lobby || !userId) return;
    if (lobby.hostId === userId) return; // host is always ready
    sendMg({ kind: "ready", from: userId });
  }, [userId, sendMg]);

  const startTossGame = useCallback(() => {
    const lobby = lobbyRef.current;
    if (!lobby || !userId || lobby.hostId !== userId) return;
    if (lobby.accepted.length < 2) return;
    if (!lobby.accepted.every((a) => lobby.ready.includes(a.userId))) return;
    const order = lobby.accepted.map((a) => a.userId);
    const names = Object.fromEntries(lobby.accepted.map((a) => [a.userId, a.name]));
    // One shared seed for the whole game — every client derives each
    // round's arena layout from it (arenaLayoutForTurn), no per-round
    // broadcast needed.
    const seed = Math.floor(Math.random() * 2_147_483_647);
    const matchId = crypto.randomUUID();
    sendMg({ kind: "start", from: userId, gameCode: lobby.gameCode, order, names, seed, matchId });
    setTossGame({
      matchId,
      core: initTossGame(order),
      names,
      hostId: userId,
      seed,
      turnStartedAt: Date.now(),
      lastFx: null,
      markers: [],
      markersKey: "main:1",
      forfeited: [],
    });
    createMinigameMatch(matchId, "target_toss", order);
    lobbyRef.current = null;
    setMinigameLobby(null);
  }, [userId, sendMg, createMinigameMatch]);

  const cancelMinigameLobby = useCallback(() => {
    const lobby = lobbyRef.current;
    if (!lobby || !userId || lobby.hostId !== userId) return;
    sendMg({ kind: "cancel", from: userId });
    lobbyRef.current = null;
    setMinigameLobby(null);
  }, [userId, sendMg]);

  const submitToss = useCallback(
    (fx: Omit<TossThrowFx, "id" | "userId">) => {
      const g = tossRef.current;
      if (!g || !userId) return;
      const turn = currentTossTurn(g.core);
      if (!turn || turn.userId !== userId) return;
      const full: TossThrowFx = { ...fx, id: `${userId}-${Date.now()}`, userId };
      sendMg({ kind: "throw", from: userId, seq: g.core.seq, ...full });
      applyToss({ userId, distance: fx.distance, seq: g.core.seq }, full);
    },
    [userId, sendMg, applyToss],
  );

  const skipTossTurn = useCallback(
    (targetId: string) => {
      const g = tossRef.current;
      if (!g || !userId) return;
      const turn = currentTossTurn(g.core);
      if (!turn || turn.userId !== targetId) return;
      sendMg({ kind: "skip", from: userId, seq: g.core.seq, target: targetId });
      applyToss({ userId: targetId, distance: null, seq: g.core.seq }, null);
    },
    [userId, sendMg, applyToss],
  );

  const dismissTossGame = useCallback(() => {
    if (tossRef.current && tossRef.current.core.winners.length > 0) setTossGame(null);
  }, []);

  // Live aim preview publisher — throttled like `pos` so drag mousemoves
  // (which fire far faster) don't flood the channel. Display-only: never
  // enters the reducer/event log.
  const sendTossAim = useCallback(
    (dxN: number, dyN: number) => {
      const g = tossRef.current;
      if (!g || !userId || !channelRef.current) return;
      const turn = currentTossTurn(g.core);
      if (!turn || turn.userId !== userId) return;
      const now = Date.now();
      if (now - lastAimSentAtRef.current < TOSS_AIM_SEND_MS) return;
      lastAimSentAtRef.current = now;
      sendMg({ kind: "aim", from: userId, dxN, dyN });
    },
    [userId, sendMg],
  );

  const clearTossAim = useCallback(() => {
    if (!userId || !channelRef.current) return;
    lastAimSentAtRef.current = 0;
    sendMg({ kind: "aim", from: userId, released: true });
  }, [userId, sendMg]);

  // "Give up" (Target Toss): broadcast the forfeit and close my own board.
  // The CALLER records my loss (GameView owns result recording); remaining
  // players fast-skip my turns, and a lone remaining player wins outright.
  const forfeitTossGame = useCallback(() => {
    const g = tossRef.current;
    if (!g || !userId || g.core.winners.length > 0 || !g.core.order.includes(userId)) return;
    sendMg({ kind: "forfeit", from: userId });
    setTossGame(null);
    setLobbyNotice("You gave up the game — it counts as a loss.");
  }, [userId, sendMg]);

  // Forfeits thin the active roster: once only ONE non-forfeited participant
  // remains, that player wins outright (decisive, per the forfeit rule —
  // never a silent cancel). Every remaining client derives this identically
  // from the same forfeited list, no extra broadcast needed.
  useEffect(() => {
    if (!tossGame || tossGame.core.winners.length > 0 || tossGame.forfeited.length === 0) return;
    const active = tossGame.core.order.filter((id) => !tossGame.forfeited.includes(id));
    if (active.length === 1) {
      setTossGame((prev) =>
        prev && prev.core.winners.length === 0 ? { ...prev, core: { ...prev.core, winners: active } } : prev,
      );
    }
  }, [tossGame]);

  const clearLobbyNotice = useCallback(() => setLobbyNotice(null), []);

  // ── Chess verbs ──────────────────────────────────────────────────────────
  const sendChessEvent = useCallback((payload: Record<string, unknown>) => {
    if (!channelRef.current) return;
    void channelRef.current.send({ type: "broadcast", event: "chess", payload });
  }, []);

  const chessChallenge = useCallback(
    (targetUserId: string) => {
      if (!channelRef.current || !userId || outgoingChessInviteTo) return;
      // One active game per pair — pre-check locally for a friendly message
      // (the DB's partial unique index is the real enforcement).
      const existing = chessGamesRef.current.find(
        (g) =>
          g.status === "active" &&
          ((g.playerAId === userId && g.playerBId === targetUserId) ||
            (g.playerBId === userId && g.playerAId === targetUserId)),
      );
      if (existing) {
        setChessNotice("You already have an active game with them — finish or cancel it first.");
        return;
      }
      setOutgoingChessInviteTo(targetUserId);
      sendChessEvent({ kind: "invite", from: userId, fromName: nameRef.current, to: targetUserId });
    },
    [userId, outgoingChessInviteTo, sendChessEvent],
  );

  const acceptChessInvite = useCallback(() => {
    const inv = incomingChessInvite;
    if (!inv || !userId) return;
    sendChessEvent({ kind: "accept", from: userId, fromName: nameRef.current, to: inv.from });
    setIncomingChessInvite(null);
    // The board opens when the challenger's "start" (with the game id) lands.
  }, [incomingChessInvite, userId, sendChessEvent]);

  const declineChessInvite = useCallback(() => {
    const inv = incomingChessInvite;
    if (!inv || !userId) return;
    sendChessEvent({ kind: "decline", from: userId, fromName: nameRef.current, to: inv.from });
    setIncomingChessInvite(null);
  }, [incomingChessInvite, userId, sendChessEvent]);

  const openChessGame = useCallback((gameId: string) => {
    setOpenChessGameId(gameId);
    setChessMinimized(false);
  }, []);
  // Minimize never forfeits — the game/subscription stays live behind the chip.
  const minimizeChessPanel = useCallback(() => setChessMinimized(true), []);
  const restoreChessPanel = useCallback(() => setChessMinimized(false), []);
  const closeChessPanel = useCallback(() => {
    // Ended games leave the list once their result panel closes.
    setChessGames((prev) => prev.filter((g) => g.status === "active"));
    setOpenChessGameId(null);
    setChessMinimized(false);
  }, []);

  const sendChessMove = useCallback(
    (gameId: string, san: string, fen: string, end?: { winnerId: string | null; reason: "checkmate" | "draw" }) => {
      const g = chessGamesRef.current.find((x) => x.id === gameId);
      if (!g || !userId || g.status !== "active" || g.currentTurn !== userId) return;
      const opponent = g.playerAId === userId ? g.playerBId : g.playerAId;
      // Moves are stored as {san, at} going forward (same jsonb column —
      // chessRowToGame still accepts old bare-string rows on read).
      const entry: ChessMoveEntry = { san, at: new Date().toISOString() };
      const history = [...g.moveHistory, entry];
      // Optimistic local apply; DB persist (allowed: it's my turn on the
      // existing row, per the RLS update policy); then the live broadcast.
      setChessGames((prev) =>
        prev.map((x) =>
          x.id === gameId
            ? {
                ...x,
                fen,
                moveHistory: history,
                currentTurn: opponent,
                status: end ? "finished" : "active",
                winnerId: end ? end.winnerId : x.winnerId,
                resultReason: end ? end.reason : x.resultReason,
                updatedAt: new Date().toISOString(),
              }
            : x,
        ),
      );
      if (supabase) {
        void supabase
          .from("chess_games")
          .update({
            board_fen: fen,
            move_history: history,
            current_turn: opponent,
            updated_at: new Date().toISOString(),
            ...(end ? { status: "finished", winner_id: end.winnerId, result_reason: end.reason } : {}),
          })
          .eq("id", gameId)
          .then(({ error }) => {
            if (error) console.error("[chess] move persist failed:", error);
          });
      }
      sendChessEvent({
        kind: "move",
        from: userId,
        gameId,
        san,
        at: entry.at,
        fen,
        ply: history.length,
        ...(end ? { status: "finished", winnerId: end.winnerId, reason: end.reason } : {}),
      });
    },
    [userId, sendChessEvent],
  );

  // "Give up" (chess resign): always decisive — my loss, their win. Works
  // off-turn via the SECURITY DEFINER RPC (RLS only lets the current-turn
  // player update the row directly).
  const resignChess = useCallback(
    (gameId: string) => {
      const g = chessGamesRef.current.find((x) => x.id === gameId);
      if (!g || !userId || g.status !== "active") return;
      if (g.playerAId !== userId && g.playerBId !== userId) return;
      const opponent = g.playerAId === userId ? g.playerBId : g.playerAId;
      setChessGames((prev) =>
        prev.map((x) =>
          x.id === gameId ? { ...x, status: "finished", winnerId: opponent, resultReason: "resignation" } : x,
        ),
      );
      if (supabase) {
        void supabase.rpc("resign_chess_game", { p_game_id: gameId }).then(({ error }) => {
          if (error) console.error("[chess] resign failed:", error);
        });
      }
      sendChessEvent({ kind: "end", from: userId, gameId, status: "finished", winnerId: opponent, reason: "resignation" });
    },
    [userId, sendChessEvent],
  );

  // Mutual cancel: propose → opponent explicitly accepts → 'abandoned' with
  // NO record_minigame_result for either side. Nobody can dodge a loss by
  // closing the app — a silent disconnect never resolves anything.
  const proposeChessCancel = useCallback(
    (gameId: string) => {
      const g = chessGamesRef.current.find((x) => x.id === gameId);
      if (!g || !userId || g.status !== "active") return;
      const opponent = g.playerAId === userId ? g.playerBId : g.playerAId;
      sendChessEvent({ kind: "cancel-propose", from: userId, fromName: nameRef.current, to: opponent, gameId });
      setChessNotice("Cancel proposed — the game ends only if your opponent accepts.");
    },
    [userId, sendChessEvent],
  );

  const respondChessCancel = useCallback(
    (gameId: string, accept: boolean) => {
      const proposal = chessCancelProposals[gameId];
      if (!proposal || !userId) return;
      setChessCancelProposals((prev) => {
        const next = { ...prev };
        delete next[gameId];
        return next;
      });
      if (!accept) {
        sendChessEvent({ kind: "cancel-decline", from: userId, to: proposal.from, gameId });
        return;
      }
      setChessGames((prev) =>
        prev.map((x) =>
          x.id === gameId ? { ...x, status: "abandoned", winnerId: null, resultReason: "mutual_cancel" } : x,
        ),
      );
      if (supabase) {
        void supabase.rpc("cancel_chess_game", { p_game_id: gameId, p_reason: "mutual_cancel" }).then(({ error }) => {
          if (error) console.error("[chess] mutual cancel failed:", error);
        });
      }
      sendChessEvent({ kind: "end", from: userId, gameId, status: "abandoned", winnerId: null, reason: "mutual_cancel" });
    },
    [userId, chessCancelProposals, sendChessEvent],
  );

  // Unreachable-opponent fallback: unilateral, no score impact. The UI gates
  // this on the opponent being absent from the room AND the game showing no
  // activity for CHESS_UNREACHABLE_GRACE_MS (MVP trust: presence history
  // isn't verifiable server-side).
  const cancelChessUnreachable = useCallback(
    (gameId: string) => {
      const g = chessGamesRef.current.find((x) => x.id === gameId);
      if (!g || !userId || g.status !== "active") return;
      setChessGames((prev) =>
        prev.map((x) =>
          x.id === gameId ? { ...x, status: "abandoned", winnerId: null, resultReason: "opponent_unreachable" } : x,
        ),
      );
      if (supabase) {
        void supabase
          .rpc("cancel_chess_game", { p_game_id: gameId, p_reason: "opponent_unreachable" })
          .then(({ error }) => {
            if (error) console.error("[chess] unreachable cancel failed:", error);
          });
      }
      sendChessEvent({ kind: "end", from: userId, gameId, status: "abandoned", winnerId: null, reason: "opponent_unreachable" });
    },
    [userId, sendChessEvent],
  );

  const clearChessNotice = useCallback(() => setChessNotice(null), []);

  // Decisive endings (checkmate/resignation) and draws fire onChessResolved
  // exactly once per game, on each PLAYER client alive to see it (a fully
  // offline player misses their record — same accepted tradeoff as the
  // notification system). Abandoned games never fire: no score impact.
  useEffect(() => {
    if (!userId) return;
    for (const g of chessGames) {
      if (g.status !== "finished") continue;
      if (g.playerAId !== userId && g.playerBId !== userId) continue;
      if (chessRecordedRef.current.has(g.id)) continue;
      chessRecordedRef.current.add(g.id);
      const opponentId = g.playerAId === userId ? g.playerBId : g.playerAId;
      const opponentName = members.find((m) => m.userId === opponentId)?.name ?? "your opponent";
      const outcome: "win" | "lose" | "tie" =
        g.resultReason === "draw" ? "tie" : g.winnerId === userId ? "win" : "lose";
      onChessResolvedRef.current(outcome, opponentName);
    }
  }, [chessGames, userId, members]);

  // AFK handling: the ACTIVE player's own client self-skips after the turn
  // timeout; if the active player has LEFT the room (gone from presence),
  // the first still-present participant in turn order acts as the skip
  // authority after a short grace (host-independent, so a departed host
  // can't stall the game either).
  useEffect(() => {
    if (!tossGame || !userId) return;
    const turn = currentTossTurn(tossGame.core);
    if (!turn) return;
    const id = setInterval(() => {
      const g = tossRef.current;
      if (!g) return;
      const t = currentTossTurn(g.core);
      if (!t) return;
      const elapsed = Date.now() - g.turnStartedAt;
      if (t.userId === userId) {
        if (elapsed >= TOSS_TURN_TIMEOUT_MS) skipTossTurn(userId);
        return;
      }
      const present = (id_: string) => id_ === userId || members.some((m) => m.userId === id_);
      // A forfeited player is "gone" even if still present in the room —
      // their turns fast-skip (short grace only, no full AFK wait).
      const gone = g.forfeited.includes(t.userId) || !present(t.userId);
      if (gone) {
        const authority = g.core.order.find((id_) => present(id_) && !g.forfeited.includes(id_));
        const wait = g.forfeited.includes(t.userId)
          ? TOSS_DEPARTED_SKIP_MS
          : TOSS_TURN_TIMEOUT_MS + TOSS_DEPARTED_SKIP_MS;
        if (authority === userId && elapsed >= wait) {
          skipTossTurn(t.userId);
        }
      }
    }, 500);
    return () => clearInterval(id);
  }, [tossGame, userId, members, skipTossTurn]);

  // Host disappears from presence before start → lobby auto-cancels locally.
  useEffect(() => {
    if (!minigameLobby || !userId || minigameLobby.hostId === userId) return;
    if (!members.some((m) => m.userId === minigameLobby.hostId)) {
      lobbyRef.current = null;
      setMinigameLobby(null);
      setLobbyNotice("The host left — game lobby closed.");
    }
  }, [members, minigameLobby, userId]);

  // Mid-game participant dwindle: if everyone else has left the room, the
  // lone remaining player shouldn't sit through rounds of auto-skips —
  // cancel the game locally (extends the host-departs-before-start rule to
  // after start).
  useEffect(() => {
    if (!tossGame || !userId || tossGame.core.winners.length > 0) return;
    // Forfeit-driven dwindling is NOT a cancel — the solo-remaining-player
    // effect above resolves it as a decisive win instead.
    const activeOrder = tossGame.core.order.filter((id) => !tossGame.forfeited.includes(id));
    if (activeOrder.length <= 1) return;
    const present = (id: string) => id === userId || members.some((m) => m.userId === id);
    const remaining = activeOrder.filter(present).length;
    if (remaining <= 1) {
      setTossGame(null);
      setLobbyNotice("Not enough players left — game cancelled.");
    }
  }, [members, tossGame, userId]);

  // RPS pick timeout: if 5s pass without both moves, cancel the game and
  // name whoever didn't pick. Each client derives this locally — moves are
  // broadcast the instant they're picked, so both sides' views agree within
  // normal latency (no cancel broadcast needed).
  useEffect(() => {
    if (!minigame || minigame.outcome || minigame.cancelled) return;
    const id = setTimeout(() => {
      setMinigame((prev) => {
        if (!prev || prev.outcome || prev.cancelled) return prev;
        const who =
          !prev.myMove && !prev.theirMove
            ? "Nobody picked in time"
            : !prev.myMove
              ? "You didn't pick in time"
              : `${prev.opponentName} didn't pick in time`;
        return { ...prev, cancelled: `${who} — game cancelled.` };
      });
    }, RPS_PICK_TIMEOUT_MS - (Date.now() - minigame.startedAt));
    return () => clearTimeout(id);
  }, [minigame]);

  // Both moves in → apply the (already-agreed, both clients computed it from
  // the same two moves) outcome exactly once.
  const minigameRewardedRef = useRef(false);
  useEffect(() => {
    if (!minigame?.outcome) {
      minigameRewardedRef.current = false;
      return;
    }
    if (minigameRewardedRef.current) return;
    minigameRewardedRef.current = true;
    // myMove can be null if I forfeited before picking — the server-side
    // resolver treats a missing move as a loss (see submit_minigame_result's
    // rps branch), same as this callback's local outcome already does.
    onMinigameResolvedRef.current(minigame.outcome, minigame.opponentName, minigame.matchId, minigame.myMove as RpsMove);
  }, [minigame]);

  return {
    selfId: userId,
    activeGroup,
    connected,
    members,
    positions,
    bubbles,
    emotes,
    chatLog,
    incomingInvite,
    outgoingInviteTo,
    battle,
    incomingGameInvite,
    outgoingGameInviteTo,
    minigame,
    lobbyInvite,
    minigameLobby,
    lobbyNotice,
    tossGame,
    tossAim,
    sendTossAim,
    clearTossAim,
    join,
    leaveRoom: teardown,
    updateMyPosition,
    sendChat,
    sendEmote,
    sendSocialPet,
    challenge,
    acceptInvite,
    declineInvite,
    clearBattle,
    inviteMinigame,
    acceptGameInvite,
    declineGameInvite,
    sendRpsMove,
    clearMinigame,
    forfeitMinigame,
    forfeitTossGame,
    createMinigameLobby,
    acceptLobbyInvite,
    declineLobbyInvite,
    toggleTossReady,
    startTossGame,
    cancelMinigameLobby,
    submitToss,
    dismissTossGame,
    clearLobbyNotice,
    chessGames,
    incomingChessInvite,
    outgoingChessInviteTo,
    chessNotice,
    clearChessNotice,
    openChessGameId,
    chessMinimized,
    chessCancelProposals,
    chessChallenge,
    acceptChessInvite,
    declineChessInvite,
    openChessGame,
    minimizeChessPanel,
    restoreChessPanel,
    closeChessPanel,
    sendChessMove,
    resignChess,
    proposeChessCancel,
    respondChessCancel,
    cancelChessUnreachable,
  };
}
